[package]
name = "windows-service-test"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
windows-service = "0.7.0"
windows-sys = { version = "0.59.0", features = ["Win32"] }
